imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@HighlightBundle/Resources/config/config.yml" }    

    
framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ MopaBootstrapBundle, DafuerGetOptGeneratorBundle, HighlightBundle ]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/opt/lessc/lib, /usr/lib/node_modules, /usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
            apply_to: "\.css$|\.less$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
            apply_to: "\.css$"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%
    spool: { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Dafuer\GetOptGeneratorBundle\Entity\User
    from_email:
        address:        team@getoptgenerator.dafuer.es
        sender_name:    "GetOptGenerator Team"        

mopa_bootstrap:
    navbar: ~
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default
        collection:
            widget_remove_btn:
                icon: trash
            widget_add_btn:
                icon: plus-sign        
    #navbar: ~
    initializr:
        google:
            analytics: UA-17161773-2
            
mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default
        
        
google:
    analytics:
        trackers:
            default:
                accountId: %google_analytics_id%
                domain:     getoptgenerator.dafuer.es
                trackPageLoadTime: true
                
highlight:
   # Each provider in this list are use on after other
   # if language given in template ins't allowed
   providers: [ geshi ]
   # All globals options can be rewrite in a specific provider
   # except cssclass who just added
   globals:
       linenos: false
       blockstyles: ""
       cssclass: highlight

   geshi:
       linenos: false
       # Two possibilities fancy or normal
       linestyle: normal
       cssclass: geshi          
       