Dafuer\GetOptGeneratorBundle\Entity\Project:
    properties:
        name:
            - NotBlank: ~ 
        description:
            - NotBlank: ~             
        language:
            - NotBlank: ~             
    getters:
        repeatedShortOption:
            - "False": { message: "Short options can not be repeated" }
        repeatedLongOption:
            - "False": { message: "Long options can not be repeated" }            
        invalidNames:
            - "False": { message: "Short or long name must be defined in every single option" }